spring.application.name=unipds-aws-notification

# AWS Credentials & Configuration
spring.cloud.aws.region.static=${AWS_REGION:us-east-1}
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID:test}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:test}
aws.ssm.parameter.template-name=${AWS_SSM_PARAMETER_NAME:/unipds/notification/template}

# Spring Mail Configuration
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:seu-email@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:sua-senha-de-app}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_SMTP_STARTTLS_ENABLE:true}

# Para testes locais com LocalStack (descomente se necessário):
# spring.cloud.aws.endpoint=${AWS_ENDPOINT:http://localhost:4566}
