#GitHub Workflow - YAML GitHub Workflow(github-workflow.json)
name: Deploy app notificação na AWS
on: [push]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout do projeto
              uses: actions/checkout@v5

            - name: Setup do Java 21
              uses: actions/setup-java@v5
              with:
                  distribution: "temurin"
                  java-version: "21"
                  cache: "maven"

            - name: Compilar o projeto
              run: mvn clean package -DskipTests

            - name: Renomear o arquivo JAR
              run: mv target/unipds-aws-notification-*.jar unipds-aws-notificacao-1.0.0.jar

            - name: Configurar credenciais da AWS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: sa-east-1

            - name: Deploy na AWS Lambda
              run: |
                  if aws lambda get-function --function-name unipds-aws-notification --region sa-east-1 >/dev/null 2>&1; then
                    echo "Função encontrada na região sa-east-1. Efetuando deploy..."
                    aws lambda update-function-code \
                      --function-name unipds-aws-notification \
                      --zip-file fileb://unipds-aws-notificacao-1.0.0.jar \
                      --region sa-east-1
                  elif aws lambda get-function --function-name unipds-aws-notification --region us-east-1 >/dev/null 2>&1; then
                    echo "Função encontrada na região us-east-1. Efetuando deploy..."
                    aws lambda update-function-code \
                      --function-name unipds-aws-notification \
                      --zip-file fileb://unipds-aws-notificacao-1.0.0.jar \
                      --region us-east-1
                  else
                    echo "❌ ERRO: A função Lambda 'unipds-aws-notification' não foi encontrada em sa-east-1 nem em us-east-1."
                    echo "Por favor, certifique-se de criar a função no Console da AWS na sua região configurada."
                    exit 1
                  fi

